#include "TextureDeclarations.hpp"

// player textures
Texture2D archer_walking_right;
Texture2D archer_walking_up;
Texture2D archer_walking_down;
Texture2D archer_shooting_right;
Texture2D archer_shooting_up;
Texture2D archer_shooting_down;
Texture2D placeholderInventoryTexture;

// tile textures
Texture2D sandtiletexture;
Texture2D watertiletexture;
Texture2D sand2tiletexture;
Texture2D water2tiletexture;
Texture2D abysstexture;
Texture2D abyss2texture;
Texture2D abyss3texture;
Texture2D snaketexture;
Texture2D snake2texture;
Texture2D snake3texture;
Texture2D treetexture;
Texture2D tree2texture;
Texture2D udltiletexture;
Texture2D udl2tiletexture;
Texture2D udl3tiletexture;
Texture2D grasstexture;
Texture2D grass2texture;
Texture2D grass3texture;

// item textures

Texture2D coralbow;
Texture2D doombow;
Texture2D bowt0;
Texture2D bowt1;
Texture2D bowt2;
Texture2D bowt3;
Texture2D bowt4;
Texture2D bowt5;
Texture2D bowt6;
Texture2D bowt7;
Texture2D bowt8;
Texture2D bowt9;
Texture2D bowt10;
Texture2D bowt11;
Texture2D bowt12;
Texture2D quivert0texture;
Texture2D quivert1texture;
Texture2D quivert2texture;
Texture2D quivert3texture;
Texture2D quivert4texture;
Texture2D quivert5texture;
Texture2D quivert6texture;
Texture2D t1leatherarmortexture;
Texture2D t2leatherarmortexture;
Texture2D t3leatherarmortexture;
Texture2D t4leatherarmortexture;
Texture2D t5leatherarmortexture;
Texture2D t6leatherarmortexture;
Texture2D t7leatherarmortexture;
Texture2D t8leatherarmortexture;
Texture2D t9leatherarmortexture;
Texture2D t10leatherarmortexture;
Texture2D t11leatherarmortexture;
Texture2D t12leatherarmortexture;
Texture2D t13leatherarmortexture;
Texture2D coralarmortexture;
Texture2D t1ringtexture;
Texture2D t2ringtexture;
Texture2D t3ringtexture;
Texture2D t4ringtexture;
Texture2D t5ringtexture;
Texture2D coralringtexture;
Texture2D blackarrowprojectiletexture;
Texture2D redkarrowprojectiletexture;
Texture2D goldarrowprojectiletexture;
Texture2D greenarrowprojectiletexture;
Texture2D bluearrowprojectiletexture;
Texture2D crossbowboltarrowprojectiletexture;
Texture2D heavycrossbowboltarrowprojectiletexture;
Texture2D redfirearrowprojectiletexture;
Texture2D coralarrowprojectiletexture;

void LoadInventoryTextures() {
    coralbow = LoadTexture("../assets/items/coral_bow.png");
    doombow = LoadTexture("../assets/items/doom_bow.png");
    bowt0 = LoadTexture("../assets/items/t0bow.png");
    bowt1 = LoadTexture("../assets/items/t1bow.png");
    bowt2 = LoadTexture("../assets/items/t2bow.png");
    bowt3 = LoadTexture("../assets/items/t3bow.png");
    bowt4 = LoadTexture("../assets/items/t4bow.png");
    bowt5 = LoadTexture("../assets/items/t5bow.png");
    bowt6 = LoadTexture("../assets/items/t6bow.png");
    bowt7 = LoadTexture("../assets/items/t7bow.png");
    bowt8 = LoadTexture("../assets/items/t8bow.png");
    bowt9 = LoadTexture("../assets/items/t9bow.png");
    bowt10 = LoadTexture("../assets/items/t10bow.png");
    bowt11 = LoadTexture("../assets/items/t11bow.png");
    bowt12 = LoadTexture("../assets/items/t12bow.png");
    quivert0texture = LoadTexture("../assets/items/t0quiver.png");
    quivert1texture = LoadTexture("../assets/items/t1quiver.png");
    quivert2texture = LoadTexture("../assets/items/t2quiver.png");
    quivert3texture = LoadTexture("../assets/items/t3quiver.png");
    quivert4texture = LoadTexture("../assets/items/t4quiver.png");
    quivert5texture = LoadTexture("../assets/items/t5quiver.png");
    quivert6texture = LoadTexture("../assets/items/t6quiver.png");
    t1leatherarmortexture = LoadTexture("../assets/items/t1leather.png");
    t2leatherarmortexture = LoadTexture("../assets/items/t2leather.png");
    t3leatherarmortexture = LoadTexture("../assets/items/t3leather.png");
    t4leatherarmortexture = LoadTexture("../assets/items/t4leather.png");
    t5leatherarmortexture = LoadTexture("../assets/items/t5leather.png");
    t6leatherarmortexture = LoadTexture("../assets/items/t6leather.png");
    t7leatherarmortexture = LoadTexture("../assets/items/t7leather.png");
    t8leatherarmortexture = LoadTexture("../assets/items/t8leather.png");
    t9leatherarmortexture = LoadTexture("../assets/items/t9leather.png");
    t10leatherarmortexture = LoadTexture("../assets/items/t10leather.png");
    t11leatherarmortexture = LoadTexture("../assets/items/t11leather.png");
    t12leatherarmortexture = LoadTexture("../assets/items/t12leather.png");
    t13leatherarmortexture = LoadTexture("../assets/items/t13leather.png");
    coralarmortexture = LoadTexture("../assets/items/coral_armor.png");
    t1ringtexture = LoadTexture("../assets/items/t1ring.png");
    t2ringtexture = LoadTexture("../assets/items/t2ring.png");
    t3ringtexture = LoadTexture("../assets/items/t3ring.png");
    t4ringtexture = LoadTexture("../assets/items/t4ring.png");
    t5ringtexture = LoadTexture("../assets/items/t5ring.png");
    greenarrowprojectiletexture = LoadTexture("../assets/projectiles/green_arrow.png");
    blackarrowprojectiletexture = LoadTexture("../assets/projectiles/black_arrow.png");
    redkarrowprojectiletexture = LoadTexture("../assets/projectiles/red_arrow.png");
    bluearrowprojectiletexture = LoadTexture("../assets/projectiles/blue_arrow.png");
    goldarrowprojectiletexture = LoadTexture("../assets/projectiles/gold_arrow.png");
    crossbowboltarrowprojectiletexture = LoadTexture("../assets/projectiles/crossbow_bolt.png");
    heavycrossbowboltarrowprojectiletexture = LoadTexture("../assets/projectiles/heavy_crowwbow_bolt.png");
    redfirearrowprojectiletexture = LoadTexture("../assets/projectiles/red_fire.png");
    coralarrowprojectiletexture = LoadTexture("../assets/projectiles/coral_arrow.png");
}
